export const PRODUCTS_DATA = [
  {
    id: 1,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image5bbc637e2e9b6.webp",
    name: "Razer Deathadder",
    price: "$69.99",
    type: "gaming",
    url: "/gaming",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 2,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image5ee353a025a66.webp",
    name: "Acer Aspire 3 A315-34",
    price: "$459.99",
    type: "laptops",
    url: "/laptops",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",

      spec10: "Spec10 is form",
    },
  },
  {
    id: 3,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/APPLE-MacBook-Pro-13-Touch-Bar-Space-Gray-MYD82-.webp",
    name: "APPLE MacBook Pro 13 Touch Bar",
    price: "$2199.99",
    type: "laptops",
    url: "/laptops",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",

      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 4,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image6176b14b5c8c8.webp",
    name: "Honor 50 Lite 128GB Blue",
    price: "$379.99",
    type: "phone",
    url: "/mobile-phones",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 5,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image61c06f7006a97.webp",
    name: "Corsair HS35 Gaming Headset",
    price: "$86.99",
    type: "gaming",
    url: "/gaming",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",

      spec10: "Spec10 is form",
    },
  },
  {
    id: 6,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image5ee353a025a66.webp",
    name: "Acer Aspire 3 A315-34",
    price: "$459.99",
    type: "laptops",
    url: "/laptops",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",

      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 7,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image5f80561c11ab7.webp",
    name: "LENOVO IdeaPad 3",
    price: "$699.99",
    type: "laptops",
    url: "/laptops",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",

      spec10: "Spec10 is form",
    },
  },
  {
    id: 8,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image5f7f1cdd52134.webp",
    name: "HP Spectre x360",
    price: "$2400.99",
    type: "laptops",
    url: "/laptops",
    specs: {
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 9,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image614ae2d1218d6.webp",
    name: "Acer Spin 3",
    price: "$1009.99",
    type: "laptops",
    url: "/laptops",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
    },
  },
  {
    id: 10,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image5e627d3b01692.webp",
    name: "HP 470 G7",
    price: "$1469.99",
    type: "laptops",
    url: "/laptops",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",

      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 11,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image61c58b9a2b6d1.webp",
    name: "GiGABYTE AORUS NViDIA RTX 3080",
    price: "$2469.99",
    type: "pc parts",
    pcpart: "gpus",
    url: "/pc-components/gpus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 12,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/INTEL-Core-i9-11900K-3.5GHz-(5.30-GHz)-97.webp",
    name: "Intel Core i9-11900k",
    price: "$799.99",
    type: "pc parts",
    pcpart: "cpus",
    url: "/pc-components/cpus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",

      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",

      spec10: "Spec10 is form",
    },
  },
  {
    id: 13,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image5fa937bc875af.webp",
    name: "AMD Ryzen 7 5800X",
    price: "$549.99",
    type: "pc parts",
    pcpart: "cpus",
    url: "/pc-components/cpus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",

      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 14,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image611a4de814b43.webp",
    name: "ASUS ROG Maximus XIII HERO",
    price: "$699.99",
    type: "pc parts",
    pcpart: "motherboards",
    url: "/pc-components/motherboards",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",

      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",

      spec10: "Spec10 is form",
    },
  },
  {
    id: 15,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "gpus",
    url: "/pc-components/gpus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
    },
  },
  {
    id: 16,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image61bc47d92a498.webp",
    name: "SAMSUNG 75TU7022",
    price: "$1369.99",
    type: "tvs",
    url: "/tvs",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",

      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
    },
  },
  {
    id: 17,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/59b914e7b8b4ea430b9feb63279e9ff9.webp",
    name: "LG 55NANO883PB",
    price: "$1399.99",
    type: "tvs",
    url: "/tvs",
    specs: {
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",

      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 18,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/PANASONIC-Televizor-TX-55JZ980E-SMART-69.webp",
    name: "PANASONIC TX-55JZ980E",
    price: "$1749.99",
    type: "tvs",
    url: "/tvs",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",

      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
    },
  },
  {
    id: 19,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image5f155487133d1.webp",
    name: "SONY KD-55XH9077",
    price: "$1099.99",
    type: "tvs",
    url: "/tvs",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",

      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 20,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image5f8eb76181f95.webp",
    name: "PHILIPS 65PUS8538 12",
    price: "$1169.99",
    type: "tvs",
    url: "/tvs",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",

      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 21,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image6148931aeaa4c.webp",
    name: "ASUS ROG Delta S",
    price: "$249.99",
    type: "gaming",
    url: "/gaming",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
    },
  },
  {
    id: 22,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/DELL-Alianware-Gaming-monitor-27-AW2720HFA-97.webp",
    name: "DELL Alienware Gaming Monitor",
    price: "$459.99",
    type: "gaming",
    url: "/gaming",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",

      spec10: "Spec10 is form",
    },
  },
  {
    id: 23,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/GIGATRON-PRIME-GAMING-FORMULA-86.webp",
    name: "GIGATRON PRIME GAMING FORMULA",
    price: "$3949.99",
    type: "gaming",
    url: "/gaming",
    specs: {
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 24,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image6141b971b08c7.webp",
    name: "LENOVO Legion 5",
    price: "$1499.99",
    type: "gaming",
    url: "/gaming",
    specs: {
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 25,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image5dee4717ed609.webp",
    name: "Cooler Master Gaming Chair CALIBER R1",
    price: "$329.99",
    type: "gaming",
    url: "/gaming",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",

      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 26,
    imageSrc: "https://img.gigatron.rs/img/products/medium/blackfr-96.webp",
    name: "Samsung Galaxy Z Fold 3",
    price: "$2149.99",
    type: "phones",
    url: "/mobile-phones",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 27,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image61b7648146325.webp",
    name: "Samsung Galaxy Z Flip 3",
    price: "$1249.99",
    type: "phones",
    url: "/mobile-phones",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 28,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image61711b27d0cf0.webp",
    name: "REALME GT Master",
    price: "$749.99",
    type: "phones",
    url: "/mobile-phones",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 29,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image5f05ae1760847.webp",
    name: "POCO F2 Pro",
    price: "$549.99",
    type: "phones",
    url: "/mobile-phones",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 30,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image61caf0982d449.webp",
    name: "APPLE iPhone 12",
    price: "$1049.99",
    type: "phones",
    url: "/mobile-phones",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 31,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "gpus",
    url: "/pc-components/gpus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 32,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "gpus",
    url: "/pc-components/gpus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 33,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "gpus",
    url: "/pc-components/gpus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 34,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "gpus",
    url: "/pc-components/gpus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 35,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "cpus",
    url: "/pc-components/cpus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 36,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "cpus",
    url: "/pc-components/cpus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 37,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "cpus",
    url: "/pc-components/cpus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 38,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "cpus",
    url: "/pc-components/cpus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 39,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "cpus",
    url: "/pc-components/cpus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 40,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "motherboards",
    url: "/pc-components/motherboards",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 41,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "motherboards",
    url: "/pc-components/motherboards",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 42,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "motherboards",
    url: "/pc-components/motherboards",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 43,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "motherboards",
    url: "/pc-components/motherboards",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 44,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "motherboards",
    url: "/pc-components/motherboards",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 45,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "cases",
    url: "/pc-components/cases",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 46,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "cases",
    url: "/pc-components/cases",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 47,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "cases",
    url: "/pc-components/cases",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 48,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "cases",
    url: "/pc-components/cases",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 49,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "ram",
    url: "/pc-components/ram",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 50,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "ram",
    url: "/pc-components/ram",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 51,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "ram",
    url: "/pc-components/ram",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 52,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "hdds",
    url: "/pc-components/hdds",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 53,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "ssds",
    url: "/pc-components/ssds",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 54,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "opticaldrives",
    url: "/pc-components/opticaldrives",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 55,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "psus",
    url: "/pc-components/psus",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
  {
    id: 56,
    imageSrc:
      "https://img.gigatron.rs/img/products/medium/image617003ff097ad.webp",
    name: "GIGABYTE AORUS Radeon RX 6900 XT",
    price: "$2169.99",
    type: "pc parts",
    pcpart: "cooling",
    url: "/pc-components/cooling",
    specs: {
      spec1: "Spec1 is this and this ,,, asdhq asd mqwoasd qweizfn",
      spec2: "Spec2 is this woasd qweizfn",
      spec3: "Spec3 is this ",
      spec4:
        "Spec4 is this and this ,,, asdhq asd mqwoasd qweizfn asdd iapsodi paois",
      spec5: "Spec5 is this and this qweizfn",
      spec6: "Spec6.",
      spec7: "Spec7 : asdasdasd",
      spec8: "Spec8 ffffff",
      spec9: "Spec9 asdasd",
      spec10: "Spec10 is form",
    },
  },
];
